//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_REST_NET_SP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculo
    {
        public int Id { get; set; }
        public int Respuesta { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
